/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3_stripes/scene.gltf')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    // actions[names[0]].reset().fadeIn(0.5).play()
    // actions[names[1]].reset().fadeIn(0.5).play()
    // actions[names[2]].reset().fadeIn(0.5).play()
  }, [])

  return (
    // scale={props.footer ? 0.5 : 1}
    <group ref={group} {...props} dispose={null} >
      <group name="Scene">
        <mesh name="Curve" geometry={nodes.Curve.geometry} material={materials['Material.001']} scale={14.44} />
        <mesh name="Curve001" geometry={nodes.Curve001.geometry} material={materials['Material.001']} scale={14.44} />
        <mesh name="Curve002" geometry={nodes.Curve002.geometry} material={materials['Material.001']} scale={14.44} />
      </group>
    </group>
  )
}

useGLTF.preload('/3_stripes/scene.gltf')
